from __future__ import annotations

from datetime import datetime
import hashlib
from typing import Literal, Optional

from pydantic import BaseModel, Field


class TTRSSArticle(BaseModel):
    # From ttrss_entries
    id: int
    title: str
    guid: str
    link: str
    updated: datetime
    content: str
    author: str
    date_entered: datetime
    comments: str
    lang: Optional[str] = None

    # From ttrss_user_entries
    int_id: int  # user_entries primary key
    feed_id: Optional[int] = None
    owner_uid: int
    marked: bool  # starred in miniflux
    published: bool  # maps to vote=-1 in miniflux
    unread: bool
    last_read: Optional[datetime] = None
    last_marked: Optional[datetime] = None
    last_published: Optional[datetime] = None
    score: int
    note: Optional[str] = None

    # From ttrss_feeds (via join) - can be NULL if feed was deleted
    feed_title: Optional[str] = None
    feed_url: Optional[str] = None

    # Aggregated data
    tags: list[str] = Field(default_factory=list)
    labels: list[str] = Field(default_factory=list)

    def to_miniflux_article(
        self, user_id: int, miniflux_feed_id: int
    ) -> MinifluxArticle:
        """
        Convert TTRSS article to Miniflux article.

        Mapping:
        - marked (starred) in TTRSS -> starred in Miniflux
        - published in TTRSS -> vote=-1 in Miniflux
        - unread in TTRSS -> status='unread'/'read' in Miniflux
        - tags + labels in TTRSS -> tags in Miniflux (combined)
        """

        # Compute hash from guid (or link as fallback)
        hash_str = hashlib.sha256((self.guid or self.link).encode()).hexdigest()

        # Determine status
        status: EntryStatus = "unread" if self.unread else "read"

        # Combine tags and labels
        all_tags = list(set(self.tags + self.labels))

        # Determine vote: published in TTRSS means vote=-1 in Miniflux
        vote = -1 if self.published else 0

        # Use last_read or updated as changed_at
        changed_at = self.last_read or self.updated

        return MinifluxArticle(
            user_id=user_id,
            feed_id=miniflux_feed_id,
            hash=hash_str,
            published_at=self.date_entered,
            title=self.title,
            url=self.link,
            author=self.author or "",
            content=self.content or "",
            status=status,
            starred=self.marked,
            comments_url=self.comments or "",
            changed_at=changed_at,
            reading_time=0,  # TTRSS doesn't track this
            created_at=self.date_entered,
            tags=all_tags,
            vote=vote,
        )


class TTRSSFeed(BaseModel):
    id: int
    owner_uid: int
    title: str
    feed_url: str
    site_url: str
    cat_id: Optional[int] = None
    category_title: Optional[str] = None
    last_updated: Optional[datetime] = None
    update_interval: int
    order_id: int

    def to_miniflux_feed(self, user_id: int, category_id: int) -> MinifluxFeed:
        """Convert TTRSS feed to Miniflux feed."""
        from datetime import datetime, timezone

        now = datetime.now(timezone.utc)

        return MinifluxFeed(
            user_id=user_id,
            category_id=category_id,
            title=self.title,
            feed_url=self.feed_url,
            site_url=self.site_url,
            checked_at=self.last_updated or now,
            next_check_at=now,
        )


EntryStatus = Literal["unread", "read", "removed"]


class MinifluxArticle(BaseModel):
    # Note: id is not included as it will be auto-generated by Miniflux
    user_id: int
    feed_id: int
    hash: str  # Will be computed from guid or link
    published_at: datetime
    title: str
    url: str
    author: str = ""  # Cannot be NULL in Go, must be empty string
    content: str = ""  # Cannot be NULL in Go, must be empty string
    status: EntryStatus = "unread"
    starred: bool = False
    comments_url: str = ""  # Cannot be NULL in Go, must be empty string
    changed_at: datetime
    reading_time: int = 0
    created_at: datetime
    tags: list[str] = Field(default_factory=list)
    vote: int = 0  # -1 for published/shared, 0 for normal, 1 for voted up


class MinifluxFeed(BaseModel):
    id: Optional[int] = None  # Auto-generated by Miniflux on insert
    user_id: int
    category_id: int
    title: str
    feed_url: str
    site_url: str
    checked_at: datetime  # Cannot be NULL in Go, must have a value
    etag_header: str = ""
    last_modified_header: str = ""
    parsing_error_msg: str = ""
    parsing_error_count: int = 0
    scraper_rules: str = ""
    rewrite_rules: str = ""
    crawler: bool = False
    username: str = ""
    password: str = ""
    user_agent: str = ""
    disabled: bool = False
    next_check_at: datetime  # Cannot be NULL in Go, must have a value
    ignore_http_cache: bool = False
    fetch_via_proxy: bool = False
    blocklist_rules: str = ""
    keeplist_rules: str = ""
    allow_self_signed_certificates: bool = False
    cookie: str = ""
    hide_globally: bool = False
    url_rewrite_rules: str = ""
    no_media_player: bool = False
    apprise_service_urls: str = ""
    disable_http2: bool = False
    description: str = ""
    ntfy_enabled: bool = False
    ntfy_priority: int = 3
    webhook_url: str = ""
    pushover_enabled: bool = False
    pushover_priority: int = 0
    ntfy_topic: str = ""
    proxy_url: str = ""
    block_filter_entry_rules: str = ""
    keep_filter_entry_rules: str = ""
